name: CI-On-Dispatch

on: repository_dispatch

jobs:

  bump_honeybee_energy:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_energy_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-energy\[standards\]==).*/honeybee-energy\[standards\]=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-energy to $VERSION"
        git push

  bump_honeybee_radiance_postprocess:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_radiance_postprocess_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-radiance-postprocess==).*/honeybee-radiance-postprocess=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-radiance-postprocess to $VERSION"
        git push

  bump_honeybee_display:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_display_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-display==).*/honeybee-display=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-display to $VERSION"
        git push

  bump_lbt_ladybug:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'lbt_ladybug_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(lbt-ladybug==).*/lbt-ladybug=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump lbt-ladybug to $VERSION"
        git push
